# 6.python异常处理

## 6.1什么是异常？

> 程序运行的过程中出现了错误

- 定义：在程序运行中，检测到一个错误，程序中止运行并且出现了一些错误的提示，也称作`bug`

- 例如：读取一个不存在的文件`f = open("C:/code/筠青.txt", "r")`

## 6.2为什么要捕获异常

> 避免程序中止，提前准备处理可能出现的异常

- 在真实工作中, 我们肯定不能因为一个小的BUG就让整个程序全部奔溃，而是对BUG进行提醒, 整个程序继续运行

## 6.3如何捕获异常

> 在可能出现异常的地方，做好提前准备，当真的出现异常的时候，可以有后续手段

### 6.3.1捕获常规异常

- 基本语法

```python
try:
    可能发生错误的代码
except:
    如果出现异常执行的代码
    
# 未发生错误try全部代码都会执行
# 未发生错误不会执行except中的代码
# 发生错误try中只会执行到报错行为止的代码
# 发生错误会执行except中的代码
```

- 使用示例

```python
try:
    print("r模式打开") # 执行
    f = open("C:/code/观止.txt", "r") # 报错
    print("r模式打开") # 不执行
except:
    print("w模式打开") # 执行
    f = open("C:/code/观止.txt", "w") # 执行
    print("w模式打开") # 执行
```

### 6.3.2捕获特定异常

- 如果尝试执行的代码的异常类型和要捕获的异常类型不一致，则无法捕获异常

- 基本语法

```python
try:
    可能发生错误的代码
except 待捕获异常名 as 别名:
    如果出现异常执行的代码
```

- 使用示例

```python
try:
    print(name) # 未定义变量，报错
except NameError as e:
    print('name变量名称未定义错误')
```

### 6.3.3捕获多个异常

- 当待捕获异常名为`Exception`可以捕获所有类型异常，作用与6.3.1一致

```python
try:
    f = open("C:/code/study.txt", "r")
except Exception as e:
    print('文件不存在')
```

- 把要捕获的异常类型的名字，放到except 后，并使用元组的方式进行书写（指定的两种异常都能捕获，未指定的无法捕获到）

```python
# 示例一：
try:
    f = open("C:/code/study.txt", "r")
except (FileNotFoundError, NameError) as e:
    print('文件不存在')
# 示例二：    
try:
    print(name)
except (FileNotFoundError, NameError) as e:
    print('名称未定义')
```

### 6.3.4其他用法

（1）打印异常信息

- 异常描述信息存贮在别名中，可以通过打印别名获取

```python
try:
    print(num) # 未定义，报错
except (NameError, ZeroDivisionError) as e:
    print(e) # 打印 name 'num' is not defined
```

（2）异常中的else

- else表示的是如果没有异常要执行的代码

```python
try:
    print("正常") # 不报错
except (NameError, ZeroDivisionError) as e:
    print(e) # 不执行
else:
    print("无异常") # 执行
```

（3）异常中的finally

- finally表示的是无论是否异常都要执行的代码
  - 之前提过，如果open文件却一直未close且程序未中止，将一直占用文件无法操作
  - 如果打开文件后发生异常，未close也将导致一直占用，因此可选择在finally中close

```python
global f
try:
    f = open("C:/code/aaa.txt", "r")
except Exception as e:
    print(e)  
finally:
    f.close() # 一定会执行close操作
```

## 6.4异常的传递

> 异常是具有传递性的(向上一级抛出)

- 当函数调用链中出现异常，如果所有函数都没有捕获异常的时候, 程序就会报错

- 利用异常具有传递性的特点, 当我们想要保证程序不会因为异常崩溃的时候, 就可以<u>在主函数中设置异常捕获</u>, 由于<u>无论在整个程序哪里发生异常, 最终都会传递到主函数中</u>, 这样就可以确保所有的异常都会被统一捕获

